Add shell-script options
kyma-incubator/local-kyma pull request #14
Opened 2020-09-18 12:13 UTC by kleino

Hi, 
thanks a lot for creating this setup-script for k3d, it has been quite helpful already :) 

One minor improvement suggestion: In its current form it could be potentially quite dangerous to use due to the missing error handling. If one of the commands fails, the other commands will still be executed. This can have unintended consequences if e.g. `k3d cluster ...` fails and the k8s-context is not updated. In that case, all the following `helm` & `kubectl` would be executed for the current which is probably not a good idea :D 
`set -o errexit` fixes that by aborting the script in case any of the commands fail. Further reading: http://www.yoone.eu/articles/2-good-practices-for-writing-shell-scripts.html

best wishes :)

2020-09-18 12:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/local-kyma-k3d?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/local-kyma-k3d?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/local-kyma-k3d?pullRequest=14) it.</sub>

2020-09-28 08:22 UTC, pbochynski requested changes
Hi Juergen,
Thanks for your PR. I like the idea, but sometimes I would like to ignore the errors - e.g. deleting some files from the resource folder. Initial idea was to make a script possible to run several times in case of some temporary errors (api-server not responding). If you run the script a second time without downloading kyma charts it will fail.

2020-09-28 11:24 UTC, kleino commented
Makes sense of course, I didnt really check that in this case.  Script errors can be ignored by adding something like `|| true` or `|| echo "completing anyway"`, e.g.
```
#script will continue even if following command fails.
docker network create k3d-kyma || echo "Network already exists"
```

2020-10-16 15:30 UTC, pbochynski commented
The PR is obsolete know, as the script got a lot of refactoring. Cluster creation is separated now from installation. Thanks for the PR - your advice will be applied in other scripts.

2020-10-16 15:30 UTC, closed without merging